spring:
  datasource:
    url: jdbc:mysql://root:YXEejCkbTKJrhYlQAmjSsPhltUjqYdvh@roundhouse.proxy.rlwy.net:47733/railway
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true