package com.sfh.pokeRogueBot.model.enums;

public enum LearnMoveReasonType {
    MOVE_IS_NOT_BETTER,
    DONT_LEARN_STATUS,
    FORGET_STATUS_ATTACK,
    FORGET_NON_POKEMON_TYPE_MOVE,
    NO_FIVE_PP_MOVES,
    DONT_LEARN_ZERO_POWER_MOVE,
    DONT_LEARN_NON_POKEMON_TYPE_MOVE,
    FORGET_WEAKER_ATTACK,
    FORGET_OTHER_TYPE

}
